/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JeppeHove-Nyborg (https://sketchfab.com/JeppeHove-Nyborg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dae-rustairborn-584d21463aca45f4aaeaff868c7918c5
Title: DAE - RustAirborn
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useEffect, useRef } from 'react'

import planeScene from '../assets/3d/plane3.glb'

const Plane2 = ({isRotating, ...props}) => {
  const ref = useRef();
  const {scene, animations} = useGLTF(planeScene);
  const {actions } =useAnimations(animations,ref);
 
  useEffect(()=>{
    if(isRotating){
      actions['Take 001'].play();
    }else{
      actions['Take 001'].stop();
    }
  },[actions,isRotating])
  return (
    <mesh {...props} ref={ref}>
      <primitive object={scene}/>
      
    </mesh>
  )
}

export default Plane2
